<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.53_YPjN' shared service.

return $this->privates['.service_locator.53_YPjN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'boatRepository' => ['privates', 'App\\Repository\\BoatRepository', 'getBoatRepositoryService.php', true],
    'game' => ['privates', '.errored..service_locator.53_YPjN.App\\Entity\\Combat', NULL, 'Cannot autowire service ".service_locator.53_YPjN": it references class "App\\Entity\\Combat" but no such service exists.'],
    'gameFunctions' => ['privates', 'App\\Service\\GameFunctions', 'getGameFunctionsService.php', true],
    'userFunction' => ['privates', 'App\\Service\\UserFunction', 'getUserFunctionService.php', true],
], [
    'boatRepository' => 'App\\Repository\\BoatRepository',
    'game' => 'App\\Entity\\Combat',
    'gameFunctions' => 'App\\Service\\GameFunctions',
    'userFunction' => 'App\\Service\\UserFunction',
]);
