<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zrGtrkU' shared service.

return $this->privates['.service_locator.zrGtrkU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AdminController::admin_editRole' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdminController::admin_users' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\GameController::attaque' => ['privates', '.service_locator.MzJN91O', 'get_ServiceLocator_MzJN91OService.php', true],
    'App\\Controller\\GameController::fight' => ['privates', '.service_locator.53_YPjN', 'get_ServiceLocator_53YPjNService.php', true],
    'App\\Controller\\GameController::start' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\ProfilController::profile' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\RankingController::index' => ['privates', '.service_locator.PAMpUhx', 'get_ServiceLocator_PAMpUhxService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.mkz8yKg', 'get_ServiceLocator_Mkz8yKgService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\AdminController:admin_editRole' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\AdminController:admin_users' => ['privates', '.service_locator.JkextnA', 'get_ServiceLocator_JkextnAService.php', true],
    'App\\Controller\\GameController:attaque' => ['privates', '.service_locator.MzJN91O', 'get_ServiceLocator_MzJN91OService.php', true],
    'App\\Controller\\GameController:fight' => ['privates', '.service_locator.53_YPjN', 'get_ServiceLocator_53YPjNService.php', true],
    'App\\Controller\\GameController:start' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\ProfilController:profile' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\RankingController:index' => ['privates', '.service_locator.PAMpUhx', 'get_ServiceLocator_PAMpUhxService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.mkz8yKg', 'get_ServiceLocator_Mkz8yKgService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\AdminController::admin_editRole' => '?',
    'App\\Controller\\AdminController::admin_users' => '?',
    'App\\Controller\\GameController::attaque' => '?',
    'App\\Controller\\GameController::fight' => '?',
    'App\\Controller\\GameController::start' => '?',
    'App\\Controller\\ProfilController::profile' => '?',
    'App\\Controller\\RankingController::index' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\AdminController:admin_editRole' => '?',
    'App\\Controller\\AdminController:admin_users' => '?',
    'App\\Controller\\GameController:attaque' => '?',
    'App\\Controller\\GameController:fight' => '?',
    'App\\Controller\\GameController:start' => '?',
    'App\\Controller\\ProfilController:profile' => '?',
    'App\\Controller\\RankingController:index' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
