<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.MzJN91O' shared service.

return $this->privates['.service_locator.MzJN91O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'game' => ['privates', '.errored..service_locator.MzJN91O.App\\Entity\\Combat', NULL, 'Cannot autowire service ".service_locator.MzJN91O": it references class "App\\Entity\\Combat" but no such service exists.'],
    'gameFunctions' => ['privates', 'App\\Service\\GameFunctions', 'getGameFunctionsService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'target' => ['privates', '.errored..service_locator.MzJN91O.App\\Entity\\Boat', NULL, 'Cannot autowire service ".service_locator.MzJN91O": it references class "App\\Entity\\Boat" but no such service exists.'],
], [
    'game' => 'App\\Entity\\Combat',
    'gameFunctions' => 'App\\Service\\GameFunctions',
    'manager' => '?',
    'target' => 'App\\Entity\\Boat',
]);
