<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.IyYPMgi' shared service.

return $this->privates['.service_locator.IyYPMgi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'game' => ['privates', '.errored..service_locator.IyYPMgi.App\\Entity\\Combat', NULL, 'Cannot autowire service ".service_locator.IyYPMgi": it references class "App\\Entity\\Combat" but no such service exists.'],
    'userFunction' => ['privates', 'App\\Service\\UserFunction', 'getUserFunctionService.php', true],
], [
    'game' => 'App\\Entity\\Combat',
    'userFunction' => 'App\\Service\\UserFunction',
]);
