<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.zkflNw6' shared service.

return $this->privates['.service_locator.zkflNw6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'service' => ['privates', 'App\\Service\\UserFunction', 'getUserFunctionService.php', true],
], [
    'service' => 'App\\Service\\UserFunction',
]);
