<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.I3PQGCb' shared service.

return $this->privates['.service_locator.I3PQGCb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'game' => ['privates', '.errored..service_locator.I3PQGCb.App\\Entity\\Combat', NULL, 'Cannot autowire service ".service_locator.I3PQGCb": it references class "App\\Entity\\Combat" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'userFunction' => ['privates', 'App\\Service\\UserFunction', 'getUserFunctionService.php', true],
], [
    'game' => 'App\\Entity\\Combat',
    'manager' => '?',
    'userFunction' => 'App\\Service\\UserFunction',
]);
