<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.XcvGfhZ' shared service.

return $this->privates['.service_locator.XcvGfhZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ProfilController::profile' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\RankingController::index' => ['privates', '.service_locator.PAMpUhx', 'get_ServiceLocator_PAMpUhxService.php', true],
    'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.mkz8yKg', 'get_ServiceLocator_Mkz8yKgService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\ProfilController:profile' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\RankingController:index' => ['privates', '.service_locator.PAMpUhx', 'get_ServiceLocator_PAMpUhxService.php', true],
    'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.mkz8yKg', 'get_ServiceLocator_Mkz8yKgService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\ProfilController::profile' => '?',
    'App\\Controller\\RankingController::index' => '?',
    'App\\Controller\\RegistrationController::register' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\ProfilController:profile' => '?',
    'App\\Controller\\RankingController:index' => '?',
    'App\\Controller\\RegistrationController:register' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
