<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.PAMpUhx' shared service.

return $this->privates['.service_locator.PAMpUhx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'service' => ['privates', 'App\\Service\\UserFunction', 'getUserFunctionService.php', true],
    'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService.php', true],
], [
    'service' => 'App\\Service\\UserFunction',
    'userRepository' => 'App\\Repository\\UserRepository',
]);
