<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\UserFunction' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/UserFunction.php';

return $this->privates['App\\Service\\UserFunction'] = new \App\Service\UserFunction();
