<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPSvzHSO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPSvzHSO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPSvzHSO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPSvzHSO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPSvzHSO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PSvzHSO',
    'container.build_id' => 'e8ba3562',
    'container.build_time' => 1576491495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPSvzHSO');
