<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvXzV6K\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvXzV6K/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRvXzV6K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRvXzV6K\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRvXzV6K\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RvXzV6K',
    'container.build_id' => 'fa0fe4ff',
    'container.build_time' => 1574933040,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvXzV6K');
